# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  androidBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev
          sudo apt install automake ant autopoint cmake build-essential libtool-bin \
              patch pkg-config protobuf-compiler ragel subversion unzip git \
              flex python wget

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '19'

      - name: Building
        run: buildsystem/compile.sh -l -a arm64
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_SDK: $ANDROID_HOME

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-${{ matrix.arch }}
          path: ./libvlcjni/libvlc/jni/obj/local/arm64-v8a/
          if-no-files-found: error
